<?php $helper = Mage::helper('merchandiser') ?>

<script type="text/javascript">
Varien.searchFormMerchandiser = Class.create();
Varien.searchFormMerchandiser.prototype = {
    initialize : function(form, field, emptyText){
        this.form   = $(form);
        this.field  = $(field);
        this.emptyText = emptyText;

        Event.observe(this.form,  'submit', this.submit.bind(this));
        Event.observe(this.field, 'focus', this.focus.bind(this));
        Event.observe(this.field, 'blur', this.blur.bind(this));
        this.blur();
    },

    submit : function(event){
        if (this.field.value == this.emptyText || this.field.value == ''){
            Event.stop(event);
            return false;
        }
        return true;
    },

    focus : function(event){
        if(this.field.value==this.emptyText){
            this.field.value='';
        }

    },

    blur : function(event){
        if(this.field.value==''){
            this.field.value=this.emptyText;
        }
    },

    initAutocomplete : function(url, destinationElement){
        new Ajax.Autocompleter(
            this.field,
            destinationElement,
            url,
            {
                paramName: this.field.name,
                method: 'get',
                minChars: 2,
                updateElement: this._selectAutocompleteItem.bind(this),
                onShow : function(element, update) {
                    if(!update.style.position || update.style.position=='absolute') {
                        update.style.position = 'absolute';
                        Position.clone(element, update, {
                            setHeight: false,
                            offsetTop: element.offsetHeight
                        });
                    }
                    Effect.Appear(update,{duration:0});
                }

            }
        );
    },

    _selectAutocompleteItem : function(element){
        if(element.title){
            var query = element.title;
            var storeid = $('store_id').value;
            var asid = $('asid').value;
            var form = $('search_mini_form');
            sendAjax(form.action+'?q='+query+'&store_id='+storeid+'&asid='+asid, form.method, 'search-results');
        }
    }
}
</script>
<form id="search_mini_form" action="<?php echo Mage::helper("adminhtml")->getUrl('merchandiser/adminhtml/search') ?>" method="get" onsubmit="submitMerchandiserSearch(this);return false;">
    <div class="form-search">
        <input id="search" type="text" name="q" value="<?php echo $this->helper('catalogsearch')->getEscapedQueryText() ?>" class="input-text" />
        <input id="store_id" type="hidden" name="store_id" value="<?php echo $this->getRequest()->getParam('store_id') ?>" />
        <input id="asid" type="hidden" name="asid" value="<?php echo $this->getRequest()->getParam('asid'); ?>" />
        <button type="submit" id="search_mini_form.submit" title="<?php echo $helper->__('Search') ?>" class="button"><span><span><?php echo $helper->__('Search') ?></span></span></button>
        <div id="search_autocomplete" class="search-autocomplete"></div>
        <script type="text/javascript">
            //<![CDATA[
            var searchForm = new Varien.searchFormMerchandiser('search_mini_form', 'search', '<?php echo $helper->__('Search entire store here...') ?>');
            //searchForm.initAutocomplete('<?php /*echo $this->helper('merchandiser')->getSuggestUrl($this->getRequest()->getParam('asid'))*/ ?>', 'search_autocomplete');
            function submitMerchandiserSearch(form) {
                var query = $('search').value;
                var storeid = $('store_id').value;
                var asid = $('asid').value;
                sendAjax(form.action+'?q='+query+'&store_id='+storeid+'&asid='+asid, form.method, 'search-results');
            } 
            //]]>
        </script>
    </div>
</form>
<div id="loading-mask">
    <img src="<?php echo $this->getSkinUrl('merchandiser/images/rule-ajax-loader.gif') ?>" alt="<?php echo $helper->__('Please wait') ?>" title="<?php echo $helper->__('Please wait') ?>" />
    <span><?php echo $helper->__('Searching...') ?></span>
</div>
<div id="search-results" class="search-results"></div>




<script type="text/javascript">

    function observerAddMassProducts(){
        jQuery('#addMassButton').unbind('click').click(function(){
           // jQuery('#addMassButton').unbind('click');  
            //jQuery('#removeMassButton').unbind('click');
            addMassProducts('<?php echo $this->getRequest()->getParam('asid'); ?>','<?php echo $helper->getProductinfoUrl() ?>');
        });
    }
    function observerRemoveMassProducts(){
        jQuery('#removeMassButton').unbind('click').click(function(){
           // jQuery('#addMassButton').unbind('click');
           // jQuery('#removeMassButton').unbind('click');
            removeMassProducts();
        });    
    }

    jQuery(document).ready(function () {
        observerAddMassProducts();
        observerRemoveMassProducts();
    });

</script>