<?php
/**
 * Layered Navigation Pro
 *
 * @category:    AdjustWare
 * @package:     AdjustWare_Nav
 * @version      2.5.1
 * @license:     3aooztWVyQyLq3pTjVKXjSrcsuymFTgXHjf7iclwH0
 * @copyright:   Copyright (c) 2013 AITOC, Inc. (http://www.aitoc.com)
 */
?>
<script type="text/javascript">
    <?php if($this->isHomePage()) :?>
        var lookhomepage = 1;
    <?php else :?>
        var lookhomepage = 0;
    <?php endif;?>
</script>