<?php if ( !($_shippingRateGroups = $this->getShippingRates()) ): ?>
	<p><?php echo Mage::getStoreConfig( 'awesomecheckout/shipping_method/no_shipping_rates_error_message' ); ?></p>
<?php else: ?>
	<dl class="sp-methods clearfix">
		<?php $shippingCodePrice = array( ); ?>
		<?php
		$_sole = count( $_shippingRateGroups ) == 1;
		foreach ( $_shippingRateGroups as $code => $_rates ):
			?>
			<dd>
				<h2><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('checkout-shipping-ft-img')->toHtml(); ?><?php echo $this->getCarrierName( $code ) ?></h2>
				<ul>
					<?php
					$_sole = $_sole && count( $_rates ) == 1;
					foreach ( $_rates as $_rate ):
						?>
						<?php $shippingCodePrice[] = "'" . $_rate->getCode() . "':" . (float) $_rate->getPrice(); ?>
						<?php $shippingCodePrice[] = "'" . $_rate->getCode() . "_total':'" . $this->helper( 'checkout' )->formatPrice( floatval( Mage::getSingleton( 'checkout/session' )->getQuote()->getGrandTotal() ) + floatval( $_rate->getPrice() ) ) . "'"; ?>
						<li class="<?php if ( $_sole ) : ?>single-item<?php else: ?>all-items<?php endif; ?>">
							<?php if ( $_rate->getErrorMessage() ): ?>
								<ul class="messages"><li class="error-msg"><ul><li><?php echo $_rate->getErrorMessage() ?></li></ul></li></ul>
							<?php else: ?>
								<?php if ( $_sole ) : ?>
									<span class="no-display"><input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>" checked="checked" /></span>
								<?php else: ?>
									<input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if ( $_rate->getCode() === $this->getAddressShippingMethod() ) echo ' checked="checked"' ?> class="radio"/>

									<?php if ( $_rate->getCode() === $this->getAddressShippingMethod() ): ?>
										<script type="text/javascript">
											//<![CDATA[
											lastPrice = <?php echo (float) $_rate->getPrice(); ?>;
											//]]>
										</script>
									<?php endif; ?>

								<?php endif; ?>
								<label for="s_method_<?php echo $_rate->getCode() ?>" style="display:block; overflow:hidden;">

									<?php $_excl = $this->getShippingPrice( $_rate->getPrice(), $this->helper( 'tax' )->displayShippingPriceIncludingTax() ); ?>
									<?php $_incl = $this->getShippingPrice( $_rate->getPrice(), true ); ?>
									<?php echo $_excl; ?>
									<span class="cost"><?php echo $_rate->getMethodTitle() ?></span>
									<?php if ( $this->helper( 'tax' )->displayShippingBothPrices() && $_incl != $_excl ): ?>
										(<?php echo $this->__( 'Incl. Tax' ); ?> <?php echo $_incl; ?>)
									<?php endif; ?>
								</label>
							<?php endif ?>
						</li>
					<?php endforeach; ?>
				</ul>
			</dd>
		<?php endforeach; ?>
	</dl>
	<script type="text/javascript">
		//<![CDATA[
	<?php if ( !empty( $shippingCodePrice ) ): ?>
			var shippingCodePrice = {<?php echo implode( ',', $shippingCodePrice ); ?>};
	<?php endif; ?>

		$$('input[type="radio"][name="shipping_method"]').each(function(el){
			Event.observe(el, 'click', function(){
				if (el.checked == true) {
					var getShippingCode = el.getValue();
	<?php if ( !empty( $shippingCodePrice ) ): ?>
						var newPrice = shippingCodePrice[getShippingCode];
						if (!lastPrice) {
							lastPrice = newPrice;
							quoteBaseGrandTotal += newPrice;
						}
						if (newPrice != lastPrice) {
							quoteBaseGrandTotal += (newPrice-lastPrice);
							lastPrice = newPrice;
						}
						var newTotal = shippingCodePrice[getShippingCode+'_total'];
						$('checkout-shipping-method-totals-wrapper').firstDescendant().innerHTML = newTotal;
	<?php endif; ?>
					checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
					return false;
				}
			});
		});
		//]]>
	</script>
<?php endif; ?>