
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php $ajaxcart = themeOptions('ajaxcart'); ?>
<div class="category-products loading">
    <div class="new-arrow1">
    <h3 class="page-title subtitle"><?php echo $this->__('Featured Products') ?></h3>
    

    </div>
    
    <?php // Grid Mode ?>
    <div id="secondary-slider" class="flexslider carousel">
    
     
    <?php if(!$_productCollection->count()): ?>
    <div id="messages_product_view">
    <ul class="messages">
        <li class="note-msg">
            <ul>
                <li>
                    <span><?php echo $this->__('There are no products matching the selection.') ?></span></li></ul></li></ul></div>
    <?php else: ?>
      <div class="slides">
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $_columnCount = 12; ?>
    <?php $i=0;$j=0; foreach ($_productCollection as $_product): ?>
    
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif; ?>
            <li style="margin-right: 24px;" class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
	    
                <?php if($ajaxcart == '2') { ?>
                
		<a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox quick-view' id='fancybox<?php echo $_product->getId()?>'><?php echo $this->__('Quick-View') ?></a>
                <?php } ?>
                
		
		<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(true)->keepAspectRatio(true)->resize(272,385) ?>" width="272" height="385" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
        
        
		<div class="productgrid-area">
		 
		    <?php	$productName = $this->htmlEscape($_product->getName());
                        if(strlen($productName) > 70) {
                                $productName = mb_strimwidth($productName,0,70,"...",'utf-8');
                        } ?>
		<h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $productName; ?></a></h3>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>

                <div class="actions">
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <div class="add_to_cart">
                    <?php if($_product->isSaleable()): ?>
			<?php if($ajaxcart == '1' || $ajaxcart == '2') { ?>
                            <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart ajx-cart" onclick="setLocationAjax2('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button> 

                            <?php } else { ?>
                                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>

                            <?php }  ?>
			<?php } else { ?>
			    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
			<?php } ?>
		    <?php else: ?>
			<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
		    <?php endif; ?>
                  </div>  
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" class="link-wishlist"><?php echo $this->__('') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" class="link-compare"><?php echo $this->__('') ?></a></li>
                        <?php endif; ?>
			
                    </ul>
                    
		 </div>
          
		</div>
		<div id='ajax_loader1<?php echo $_product->getId()?>' class="ajaxcartpro_progress1" style="display: none;">
		    <img src="<?php echo $this->getSkinUrl('ajaxcart/images/al.gif'); ?>">
		    <p><?php echo $this->__('Please wait...') ?></p>
		    <div><?php echo $this->__('We are updating Shopping Bag.') ?></div>
		</div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif; ?>
    
        <?php endforeach ?>
	</div>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
	  <?php endif; ?>
    </div>
  
</div>
<script type="text/javascript">

j$('#secondary-slider').flexslider({
	 selector: ".slides > ul",
	  animation: "slide",
	  animationLoop: false,
	  itemWidth: 871,
	  itemMargin: 0,
	  minItems: 1,
	  maxItems: 1,
	  move:1,
	  controlNav: false,
	  slideshowSpeed: 7000,          
	  animationSpeed: 1000,
	  slideshow: false,
	  start: function(slider){
	    j$('div').removeClass('loading');
	  }
       });
</script>

<script type="text/javascript">
     <?php if($ajaxcart == '1' || $ajaxcart == '2') { ?>
	jQuery.noConflict();
	
	jQuery('.fancybox').live('click', function() {
	    jQuery('#fancybox-loading').show();
        });
	
	jQuery('.fancybox').fancybox(
			{
			   hideOnContentClick : true,
			   width: 630,
			   autoDimensions: true,
               type : 'iframe',
			   showTitle: false,
			   scrolling: 'no',
			   onComplete: function(){
				jQuery('#fancybox-frame').load(function() { // wait for frame to load and then gets it's height
					jQuery('#fancybox-loading').hide();
					jQuery('#fancybox-content').height(jQuery(this).contents().find('body').height()+30);
					jQuery.fancybox.resize();
				 });

			   }
			}
		);
	
	function showOptions(id){
		jQuery('#fancybox'+id).trigger('click');
	}	
	
	function setAjaxData2(data,iframe){
		if(data.status == 'ERROR'){
			alert(data.message);
		}else{
		    successMessage(data.message);
			if(jQuery('.block-cart')){
	            jQuery('.block-cart').replaceWith(data.sidebar);
	        }
	        if(jQuery('.header .links')){
	            jQuery('.header .links').replaceWith(data.toplink);
	        }
	        jQuery.fancybox.close();
		}
	}
	function setLocationAjax2(url,id){
	    if (window.location.protocol == "https:") {
                
                url=url.replace("http://","https://");  
            }
		url += 'isAjax/1';
		url = url.replace("checkout/cart","ajax/index");
		jQuery('#ajax_loader1'+id).show();
		
		try {
			jQuery.ajax( {
				url : url,
				dataType : 'json',
				success : function(data) {
					jQuery('#ajax_loader1'+id).hide();
         			setAjaxData2(data,false);           
				}
			});
		} catch (e) {
		}
	}
	 <?php  } ?>
</script>
	