<?php $_dld_color_title = Mage::helper('dailydeal')->getConfigSchemeColor(); ?>
<?php $_dld_color_coundown = Mage::helper('dailydeal')->getConfigCountdownColor(); ?>
<?php $_dld_color_lighight = Mage::helper('dailydeal')->getConfigHighlightColor(); ?> 
<?php
	function colourBrightnesstab($hex, $percent) {
	$hash = '';
	if (stristr($hex,'#')) {
		$hex = str_replace('#','',$hex);
		$hash = '#';
	}
	/// HEX TO RGB
	$rgb = array(hexdec(substr($hex,0,2)), hexdec(substr($hex,2,2)), hexdec(substr($hex,4,2)));
	//// CALCULATE
	for ($i=0; $i<3; $i++) {
		// See if brighter or darker
		if ($percent > 0) {
			// Lighter
			$rgb[$i] = round($rgb[$i] * $percent) + round(255 * (1-$percent));
		} else {
			// Darker
			$positivePercent = $percent - ($percent*2);
			$rgb[$i] = round($rgb[$i] * $positivePercent) + round(0 * (1-$positivePercent));
		}
		// In case rounding up causes us to go to 256
		if ($rgb[$i] > 255) {
			$rgb[$i] = 255;
		}
	}
	//// RBG to Hex
	$hex = '';
	for($i=0; $i < 3; $i++) {
		// Convert the decimal digit to hex
		$hexDigit = dechex($rgb[$i]);
		// Add a leading zero if necessary
		if(strlen($hexDigit) == 1) {
		$hexDigit = "0" . $hexDigit;
		}
		// Append to the hex string
		$hex .= $hexDigit;
	}
	return $hash.$hex;
}
?>

<style type="text/css">
	.tab-deal td.active a span ,
	.tab-deal td a:hover span{ background: <?php echo $_dld_color_title; ?>; background: <?php echo colourBrightnesstab($_dld_color_title,0.9);?> linear-gradient(to bottom, <?php echo colourBrightnesstab($_dld_color_title,0.9);?>, <?php echo colourBrightnesstab($_dld_color_title,-0.7);?>);}
	.tab-deal td.active a span span ,
	.tab-deal td a:hover span span{background: none;}
</style>
<table class="tab-deal">
    <tr>
        <td class="active">
            <a href="<?php echo Mage::helper('dailydeal')->getUrlHttp('dailydeal/index'); ?>">
                <span><span><?php echo $this->__('Current Deals'); ?></span></span>
            </a>
        </td>
        <td>
            <a href="<?php echo Mage::helper('dailydeal')->getUrlHttp('dailydeal/past'); ?>">
                <span><span><?php echo $this->__('Past Deals'); ?></span></span>
            </a>
        </td>
        <td>
            <a href="<?php echo Mage::helper('dailydeal')->getUrlHttp('dailydeal/comming'); ?>">
                <span><span><?php echo $this->__('Upcoming Deals'); ?></span></span>
            </a>
        </td>
    </tr>
</table>

<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $ajaxcart = themeOptions('ajaxcart');
    $_productCollection=$this->getLoadedProductCollection();
    $columnCount = themeOptions('column_count');
    $this->setColumnCount($columnCount);
    $_helper = $this->helper('catalog/output');
?>
<?php
$_activedealsCollection = $this->getActivedeals();
$_helper = $this->helper('catalog/output');
?>
<?php if (!$_activedealsCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products list-actdeals">
        <?php echo $this->getToolbarHtml() ?>
        <?php // List mode ?>
        <?php if ($this->getMode() != 'grid'): ?>
            <?php $_iterator = 0; ?>
            <ol class="products-list" id="products-list">
                <?php foreach ($_activedealsCollection as $_activedeal): ?>
                    <?php
                    $dealqty = $_activedeal->getDealQty();
                    $soldqty = $_activedeal->getSoldQty();
                    $_product = Mage::getModel('catalog/product')->load($_activedeal->getProductId());
                    ?>
                    <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
                    <!-- 
                    <li class="column3 item<?php if (++$_iterator == sizeof($_activedealsCollection)): ?> last<?php endif; ?>">
                    -->
                    <?php if($ajaxcart == '2') { ?>
		<a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox quick-view' id='fancybox<?php echo $_product->getId()?>'><?php echo $this->__('Quick-View') ?></a>
            <?php } ?>
                        <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(true)->keepAspectRatio(true)->resize(232,256); ?>" width="232" height="256" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <?php echo Mage::helper('core/mwdailydeal')->showImage($_product); ?>
                        <?php // Product description ?>
                        <div class="product-shop">
                            <div class="f-fix">
                                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a></h2>
                                <?php if ($_product->getRatingSummary()): ?>
                                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                                <?php endif; ?>
							<?php /*----- display daily deal -----*/ ?>
							<?php 
								$countdown = $this->getLayout()->createBlock('dailydeal/deal');
								$countdown->setData('product', $_product);
								echo $countdown->setTemplate('mw_dailydeal/catalog/product/countdown.phtml')->toHtml(); 
							?>
							<?php /*----- end display daily deal -----*/ ?>
                                <?php echo $this->getPriceHtml($_product, true) ?>

                                <div class="mwdld_coming_date">
                                    <?php if ($soldqty > 1 || $soldqty == 0) { ?>
                                        <?php echo Mage::helper('dailydeal')->__('There are <span class="deal-qty-one">%s items</span> sold.', $soldqty); ?> 				
                                    <?php } elseif ($soldqty == 1) { ?>
                                        <?php echo Mage::helper('dailydeal')->__('There are <span class="deal-qty-one">%s items</span> sold.', $soldqty); ?> 				
                                    <?php } ?>	            
                                </div>
                                <div class="desc std">
                                    <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                                </div>

                                <ul class="add-to-links">
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                    <?php endif; ?>
                                    <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                    <?php endif; ?>
                                </ul>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

        <?php else: ?>

            <?php // Grid Mode  ?>

            <?php
            $_collectionSize = $_activedealsCollection->count();
            $columncount = Mage::getStoreConfig('dailydeal/general/columncount'); //echo $columncount;die;
            $_columnCount = $columncount ? $columncount : 3; //$this->getColumnCount(); echo $_columnCount;die;
            
            	    if($_columnCount == 4){
            $imgwidth = 197;
            
            }elseif($_columnCount == 2){
             $imgwidth = 422;
            
            
	    }elseif($_columnCount == 3){
             $imgwidth = 272;
             
           
	
	    }
        
            ?>
            <?php
            $i = 0;
            foreach ($_activedealsCollection as $_activedeal):
                ?>
                <?php
                $dealqty = $_activedeal->getDealQty();
                $soldqty = $_activedeal->getSoldQty();

                $_product = Mage::getModel('catalog/product')->load($_activedeal->getProductId());
                ?>
                <?php if ($i++ % $_columnCount == 0): ?>
                    <ul class="products-grid">
                    <?php endif ?>
                    <li class="column<?php echo $_columnCount ?> item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                    
                    		 <?php if($ajaxcart == '2') { ?>
		<a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox quick-view' id='fancybox<?php echo $_product->getId()?>'><?php echo $this->__('Quick-View') ?></a>
                <?php } ?>
                
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(true)->keepAspectRatio(true)->resize($imgwidth,385); ?>" width="<?php echo $imgwidth;?>" height="385" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                            <?php echo Mage::helper('core/mwdailydeal')->showImage($_product); ?>
                            
                       <div class="mw_pro_dld productgrid-area">
							<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
							<?php /*----- display daily deal -----*/ ?>
							<?php 
								$countdown = $this->getLayout()->createBlock('dailydeal/deal');
								$countdown->setData('product', $_product);
								echo $countdown->setTemplate('mw_dailydeal/catalog/product/countdown.phtml')->toHtml(); 
							?>
							<?php /*----- end display daily deal -----*/ ?>
							<?php if($_product->getRatingSummary()): ?>
								<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
							<?php endif; ?>
							<?php echo $this->getPriceHtml($_product, true) ?>
							
						</div>
                        <div class="actions">
                    <?php if($_product->isSaleable()): ?>
			<?php if($ajaxcart == '1' || $ajaxcart == '2') { ?>
			    <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
			    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart ajx-cart" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button> 
			    
			    <?php } else { ?>
				    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
				    
			    <?php }  ?>
			<?php } else { ?>
			    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
			<?php } ?>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" class="link-wishlist"><?php echo $this->__('') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" class="link-compare"><?php echo $this->__('') ?></a></li>
                        <?php endif; ?>
                       
                    </ul>
                    
                </div>
                    </li>
                    <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
                    </ul>
                <?php endif ?>
            <?php endforeach ?>
            <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        <?php endif; ?>

        <div class="toolbar-bottom">
            <?php echo $this->getToolbarHtml() ?>
        </div>
    </div>
<?php endif; ?>
<script type="text/javascript">
     <?php if($ajaxcart == '1' || $ajaxcart == '2') { ?>
	jQuery.noConflict();
	
	jQuery('.fancybox').live('click', function() {
	    jQuery('#fancybox-loading').show();
        });
	
	jQuery('.fancybox').fancybox(
			{
			   hideOnContentClick : true,
			   width: 630,
			   autoDimensions: true,
               type : 'iframe',
			   showTitle: false,
			   scrolling: 'no',
			   onComplete: function(){
				jQuery('#fancybox-frame').load(function() { // wait for frame to load and then gets it's height
					jQuery('#fancybox-loading').hide();
					jQuery('#fancybox-content').height(jQuery(this).contents().find('body').height()+30);
					jQuery.fancybox.resize();
				 });

			   }
			}
		);
	
	function showOptions(id){
		jQuery('#fancybox'+id).trigger('click');
	}
		
	function setAjaxData(data,iframe){
		if(data.status == 'ERROR'){
			alert(data.message);
		}else{
		    successMessage(data.message);
			if(jQuery('.block-cart')){
	            jQuery('.block-cart').replaceWith(data.sidebar);
	        }
	        if(jQuery('.header .links')){
	            jQuery('.header .links').replaceWith(data.toplink);
	        }
	        jQuery.fancybox.close();
		}
	}
	function setLocationAjax(url,id){
		url += 'isAjax/1';
		url = url.replace("checkout/cart","ajax/index");
		jQuery('#ajax_loader'+id).show();
		try {
			jQuery.ajax( {
				url : url,
				dataType : 'json',
				success : function(data) {
					jQuery('#ajax_loader'+id).hide();
         			setAjaxData(data,false);           
				}
			});
		} catch (e) {
		}
	}
	 <?php } ?>
</script>