<?php $_dld_color_title = Mage::helper('dailydeal')->getConfigSchemeColor(); ?>
<?php $_dld_color_coundown = Mage::helper('dailydeal')->getConfigCountdownColor(); ?>
<?php $_dld_color_lighight = Mage::helper('dailydeal')->getConfigHighlightColor(); ?> 
<?php
	function colourBrightnesstab($hex, $percent) {
	$hash = '';
	if (stristr($hex,'#')) {
		$hex = str_replace('#','',$hex);
		$hash = '#';
	}
	/// HEX TO RGB
	$rgb = array(hexdec(substr($hex,0,2)), hexdec(substr($hex,2,2)), hexdec(substr($hex,4,2)));
	//// CALCULATE
	for ($i=0; $i<3; $i++) {
		// See if brighter or darker
		if ($percent > 0) {
			// Lighter
			$rgb[$i] = round($rgb[$i] * $percent) + round(255 * (1-$percent));
		} else {
			// Darker
			$positivePercent = $percent - ($percent*2);
			$rgb[$i] = round($rgb[$i] * $positivePercent) + round(0 * (1-$positivePercent));
		}
		// In case rounding up causes us to go to 256
		if ($rgb[$i] > 255) {
			$rgb[$i] = 255;
		}
	}
	//// RBG to Hex
	$hex = '';
	for($i=0; $i < 3; $i++) {
		// Convert the decimal digit to hex
		$hexDigit = dechex($rgb[$i]);
		// Add a leading zero if necessary
		if(strlen($hexDigit) == 1) {
		$hexDigit = "0" . $hexDigit;
		}
		// Append to the hex string
		$hex .= $hexDigit;
	}
	return $hash.$hex;
}
?>

<style type="text/css">
	.tab-deal td.active a span ,
	.tab-deal td a:hover span{background: <?php echo $_dld_color_title; ?>; background: <?php echo colourBrightnesstab($_dld_color_title,0.9);?> linear-gradient(to bottom, <?php echo colourBrightnesstab($_dld_color_title,0.9);?>, <?php echo colourBrightnesstab($_dld_color_title,-0.7);?>);}
	.tab-deal td.active a span span ,
	.tab-deal td a:hover span span{background: none;}
	.deal-time{color: <?php echo $_dld_color_lighight;?>;}
	.mwdld_coming_date{border-bottom: 1px dotted <?php echo $_dld_color_title?>; border-top: 1px dotted <?php echo $_dld_color_title?>; background: <?php echo colourBrightnesstab($_dld_color_title,0.1);?>;}

</style>

<table class="tab-deal">
    <tr>
        <td>
            <a href="<?php echo Mage::helper('dailydeal')->getUrlHttp('dailydeal/index'); ?>">
                <span><span><?php echo $this->__('Current Deals'); ?></span></span>
            </a>
        </td>
        <td>
            <a href="<?php echo Mage::helper('dailydeal')->getUrlHttp('dailydeal/past'); ?>">
                <span><span><?php echo $this->__('Past Deals'); ?></span></span>
            </a>
        </td>
        <td class="active">
            <a href="<?php echo Mage::helper('dailydeal')->getUrlHttp('dailydeal/comming'); ?>">
                <span><span><?php echo $this->__('Upcoming Deals'); ?></span></span>
            </a>
        </td>
    </tr>
</table>

<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
	$_coreHelper = $this->helper('core');
	$_taxHelper  = $this->helper('tax');
    $_commingdealsCollection=$this->getCommingdeals();
    $_helper = $this->helper('catalog/output');
 	$outputFormat = Mage::app()->getLocale()->getDateTimeFormat(Mage_Core_Model_Locale::FORMAT_TYPE_LONG);
    
?>
<?php if(!$_commingdealsCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_commingdealsCollection as $_commingdeal): ?>
    <?php 
    $_id = $_commingdeal->getId();
    $dealqty = $_commingdeal->getDealQty();
    $_product = Mage::getModel('catalog/product')->load($_commingdeal->getProductId());?>
        <li class="item<?php if( ++$_iterator == sizeof($_commingdealsCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <!--
             <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            -->
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(true)->keepAspectRatio(true)->resize(232,256); ?>" width="232" height="256" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
			<?php // Product description ?>
			<div class="product-shop">
				<div class="f-fix">
					<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
					<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a></h2>
					<?php if ($_product->getRatingSummary()): ?>
						<?php echo $this->getReviewsSummaryHtml($_product) ?>
					<?php endif; ?>
					<?php echo $this->getPriceHtml($_product, true) ?>
                    


					<?php /*----- display daily deal -----*/ ?>
					<?php $startdatetime= strtotime($_commingdeal->getStartDateTime()); ?>
					<div class="mwdld_coming_date">
						<?php echo Mage::helper('dailydeal')->__('Deal starts at: <span class="deal-time">%s</span><h4 class="deal-time">%s</h4>',date(' H:i',$startdatetime), date(' d F, Y',$startdatetime)); ?> 
					</div>
					<?php /*----- end display daily deal -----*/ ?>
					<div class="desc std">
						<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
					</div>
				</div>
			</div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>
    <?php $_collectionSize = $_commingdealsCollection->count() ?>
    
   
    <?php
	
	    $_columnCount = $this->getColumnCount();
	    
	    if($_columnCount == 4){
            $imgwidth = 197;
            
            }elseif($_columnCount == 2){
             $imgwidth = 422;
            
            
	    }elseif($_columnCount == 3){
             $imgwidth = 272;
             
           
	
	    }
	?>
    <?php 
    	$_collectionSize = $_commingdealsCollection->count(); 
    	$columncount = Mage::getStoreConfig('dailydeal/general/columncount'); //echo $columncount;die;
        $_columnCount = $columncount ? $columncount : 3; //$this->getColumnCount(); echo $_columnCount;die;
    ?>
    <?php $i=0; foreach ($_commingdealsCollection as $_commingdeal): ?>
    <?php
        $_id = $_commingdeal->getId();
        $dealqty = $_commingdeal->getDealQty();
        $_product = Mage::getModel('catalog/product')->load($_commingdeal->getProductId());
    ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="column<?php echo $_columnCount ?> item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
            <?php if($ajaxcart == '2') { ?>
		<a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox quick-view' id='fancybox<?php echo $_product->getId()?>'><?php echo $this->__('Quick-View') ?></a>
                <?php } ?>
            <!--
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
            
            -->
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(true)->keepAspectRatio(true)->resize($imgwidth,385); ?>" width="<?php echo $imgwidth;?>" height="385" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                 <div class="mw_pro_dld productgrid-area">
                 <!--
                 
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                 -->
					<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
					<?php if($_product->getRatingSummary()): ?>
						<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
					<?php endif; ?>
					<?php  echo $this->getPriceHtml($_product, true) ?>
                    

                    
				 </div>
				 <div class="actions">
					<?php /*----- display daily deal -----*/ ?>
					 <?php $startdatetime= strtotime($_commingdeal->getStartDateTime()); ?>
					<div class="mwdld_coming_date add-to-links">
						<?php echo Mage::helper('dailydeal')->__('Deal starts at <span class="deal-time">%s</span><span class="deal-time deal-date">%s</span>',date(' H:i',$startdatetime), date(' d F, Y',$startdatetime)); ?> 
					</div>
					<?php /*----- end display daily deal -----*/ ?>
				</div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>

<script type="text/javascript">
     <?php if($ajaxcart == '1' || $ajaxcart == '2') { ?>
	jQuery.noConflict();
	
	jQuery('.fancybox').live('click', function() {
	    jQuery('#fancybox-loading').show();
        });
	
	jQuery('.fancybox').fancybox(
			{
			   hideOnContentClick : true,
			   width: 630,
			   autoDimensions: true,
               type : 'iframe',
			   showTitle: false,
			   scrolling: 'no',
			   onComplete: function(){
				jQuery('#fancybox-frame').load(function() { // wait for frame to load and then gets it's height
					jQuery('#fancybox-loading').hide();
					jQuery('#fancybox-content').height(jQuery(this).contents().find('body').height()+30);
					jQuery.fancybox.resize();
				 });

			   }
			}
		);
	
	function showOptions(id){
		jQuery('#fancybox'+id).trigger('click');
	}
		
	function setAjaxData(data,iframe){
		if(data.status == 'ERROR'){
			alert(data.message);
		}else{
		    successMessage(data.message);
			if(jQuery('.block-cart')){
	            jQuery('.block-cart').replaceWith(data.sidebar);
	        }
	        if(jQuery('.header .links')){
	            jQuery('.header .links').replaceWith(data.toplink);
	        }
	        jQuery.fancybox.close();
		}
	}
	function setLocationAjax(url,id){
		url += 'isAjax/1';
		url = url.replace("checkout/cart","ajax/index");
		jQuery('#ajax_loader'+id).show();
		try {
			jQuery.ajax( {
				url : url,
				dataType : 'json',
				success : function(data) {
					jQuery('#ajax_loader'+id).hide();
         			setAjaxData(data,false);           
				}
			});
		} catch (e) {
		}
	}
	 <?php } ?>
</script>