<div class="video-banner row">
    <ul>
        <li class="panel col-xs-12 col-sm-4 col-md-4 col-lg-4">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home-block2')->toHtml() ?>
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home-block11')->toHtml() ?>
        </li>
        <li class="panel col-xs-12 col-sm-4 col-md-4 col-lg-4">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('searchbrand-topic')->toHtml() ?>
        </li>
        <li class="panel col-xs-12 col-sm-4 col-md-4 col-lg-4">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home-video-right')->toHtml() ?>
        </li>
    </ul>
    <div class="clearfix"></div>
</div>