<fieldset>
	<div class="col-1">
		<table class="merchandiser-hint-table">
			<tr>
				<td><img src="http://www.ontapgroup.com/logos/mer_21.png" /></td>
				<td>&nbsp;</td>
				<td>
					<h3>Visual Merchandiser <?php echo Mage::helper('merchandiser')->getExtensionVersion() ?></h3>
					<?php $link = "http://www.ontapgroup.com/magento/customer/account"; ?>
					<p><?php echo Mage::helper('merchandiser')->__("For support, visit <a href='%s' target='_blank'>%s</a>, login and then raise a Support Ticket." , $link,$link) ?></p>
				</td>
			</tr>
		</table>
    </div>
</fieldset>