<?php
$key = Mage::getSingleton('adminhtml/url')->getSecretKey('merchandiser', 'adminhtml_saveOrdering');

   // $oldKey = Mage::getSingleton('core/session')->getData('_form_key');
  //  Mage::getSingleton('core/session')->setData('_form_key', $newKey);
    $url = $this->getUrl('merchandiser/adminhtml/saveOrdering');
   // Mage::getSingleton('core/session')->setData('_form_key', $oldKey);

?>
<button type="button" class="button" onclick="var f=$('product-ordering-form'); f.action='<?php echo $url ?>';showDimWindow(); removeResults(); f.submit(); ">
	<span><span><?php echo Mage::helper('merchandiser')->__('Save positions') ?></span></span>
</button>

<div id = "dimwindow" ></div>
<div id="dimwindow-inner">
	<img src ="<?php echo $this->getSkinUrl('merchandiser/images/rule-ajax-loader.gif') ?>" >
	<?php echo Mage::helper('merchandiser')->__('Saving category'); ?>
</div>
