<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
</head>
<body>
	<div class="header">
		<?php echo $this->getChildHtml('header') ?>
	</div>
	<div class="main">
	   <div class="col-main">
	   		<?php echo $this->getChildHtml('content') ?>
	   </div>
	   <div class="col-right sidebar">
	   		<?php echo $this->getChildHtml('right') ?>
	        <div id="searchRequestResult"></div>
	   </div>
	</div>
</body>
</html>
