
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>

<?php
$layout = themeOptions('productlayout');

if ($layout == null || $layout == 'default')
{ ?>


<?php
$mainImagePath = '';
$galleryImages = $this->getGalleryImages();
if (count($galleryImages) > 0) {
   
    
    $gallery .= '<div id="slider" class="flexslider"><ul class="slides">';
    foreach ($galleryImages as $_image) {
        if ($_image->getFile() == $_product->getData('small_image')) {
            $mainImagePath = $this->getGalleryUrl($_image);
        }
        $gallery .= '<li>'
                 .  '<a href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
                 .  'rel="popupWin:\'' . $this->getGalleryUrl($_image) . '\', useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) .  '\'" class="cloud-zoom-gallery" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                 .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->constrainOnly(true)->keepAspectRatio(true)->resize(77,77) . '" width="77" height="77" alt="' . $this->htmlEscape($_image->getLabel()) . '" />'
                 .  '</a></li>';
    }
    $gallery .= '</ul></div>';
}
?>

<?php
}
elseif ($layout == 'horizontal')
{ ?>


<?php
$mainImagePath = '';
$galleryImages = $this->getGalleryImages();
if (count($galleryImages) > 0) {
    
    $gallery .= '<div id="slider" class="flexslider"><ul class="slides">';
    foreach ($galleryImages as $_image) {
        if ($_image->getFile() == $_product->getData('small_image')) {
            $mainImagePath = $this->getGalleryUrl($_image);
        }
        $gallery .= '<li>'
                 .  '<a href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
                 .  'rel="popupWin:\'' . $this->getGalleryUrl($_image) . '\', useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) .  '\'" class="cloud-zoom-gallery" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                 .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->constrainOnly(true)->keepAspectRatio(true)->resize(77,77) . '" width="77" height="77" alt="' . $this->htmlEscape($_image->getLabel()) . '" />'
                 .  '</a></li>';
    }
    $gallery .= '</ul></div>';
}
?>

<?php
}
elseif ($layout == 'vertical')
{ ?>


<?php
$mainImagePath = '';
$galleryImages = $this->getGalleryImages();
if (count($galleryImages) > 0) {
    
    $gallery .= '<div id="slider" class="flexslider"><ul class="slides">';
    foreach ($galleryImages as $_image) {
        if ($_image->getFile() == $_product->getData('small_image')) {
            $mainImagePath = $this->getGalleryUrl($_image);
        }
        $gallery .= '<li>'
                 .  '<a href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
                 .  'rel="popupWin:\'' . $this->getGalleryUrl($_image) . '\', useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) .  '\'" class="cloud-zoom-gallery" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                 .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->constrainOnly(true)->keepAspectRatio(true)->resize(77,77) . '" width="77" height="77" alt="' . $this->htmlEscape($_image->getLabel()) . '" />'
                 .  '</a></li>';
    }
    $gallery .= '</ul></div>';
}
?>


<?php
}
?>




<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<p class="product-image product-image-zoom">
    <a rel="<?php echo $this->renderCloudOptions(); ?>" gallery="<?php echo $mainImagePath; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class="cloud-zoom" id="cloudZoom">
    <?php
        $_img = '<img id="image" src="'.$this->getCloudImage($_product)->constrainOnly(true)->keepAspectRatio(true).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
    </a>
</p>

<?php
if ($layout == null || $layout == 'default')
{ ?>

    <?php if(isset($gallery)): ?>
        
        <div class="default-views more-views">
            

        <?php echo $gallery; ?>
        
        
        
        </div>
    <?php endif; ?>
 
 <?php
}
elseif ($layout == 'horizontal')
{ ?>   
    
    <?php if(isset($gallery)): ?>
        
        <div class="horizontal-views more-views">
            
            
        
        
        <?php echo $gallery; ?>

        
        
        </div>
    <?php endif; ?>
    
    
    <?php
}
elseif ($layout == 'vertical')
{ ?>
    
    <?php if(isset($gallery)): ?>
        
        <div class="vertical-views more-views">
            
            
        
        
        <?php echo $gallery; ?>
        
        
        
        </div>
    <?php endif; ?>
    
    
    <?php
}
?>
    
<?php else: ?>
<p class="product-image">
    <?php
        $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->keepFrame(false)->resize(300,498).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>
<?php endif; ?>

<script>
  j$('#slider').flexslider({
    animation: "slide",
    animationLoop: false,
    itemWidth: 86,
    itemMargin: 9,
   // minItems: 3,
   // maxItems: 3,
    //move:1,
    controlNav: false,
    slideshow: false
  });
</script>
