<?php $_dld_color_title = Mage::helper('dailydeal')->getConfigSchemeColor(); ?>
<?php $_dld_color_coundown = Mage::helper('dailydeal')->getConfigCountdownColor(); ?>
<?php $_dld_color_lighight = Mage::helper('dailydeal')->getConfigHighlightColor(); ?>
<?php
function colourBrightnesstab($hex, $percent) {
    $hash = '';
    if (stristr($hex,'#')) {
        $hex = str_replace('#','',$hex);
        $hash = '#';
    }
    /// HEX TO RGB
    $rgb = array(hexdec(substr($hex,0,2)), hexdec(substr($hex,2,2)), hexdec(substr($hex,4,2)));
    //// CALCULATE
    for ($i=0; $i<3; $i++) {
        // See if brighter or darker
        if ($percent > 0) {
            // Lighter
            $rgb[$i] = round($rgb[$i] * $percent) + round(255 * (1-$percent));
        } else {
            // Darker
            $positivePercent = $percent - ($percent*2);
            $rgb[$i] = round($rgb[$i] * $positivePercent) + round(0 * (1-$positivePercent));
        }
        // In case rounding up causes us to go to 256
        if ($rgb[$i] > 255) {
            $rgb[$i] = 255;
        }
    }
    //// RBG to Hex
    $hex = '';
    for($i=0; $i < 3; $i++) {
        // Convert the decimal digit to hex
        $hexDigit = dechex($rgb[$i]);
        // Add a leading zero if necessary
        if(strlen($hexDigit) == 1) {
            $hexDigit = "0" . $hexDigit;
        }
        // Append to the hex string
        $hex .= $hexDigit;
    }
    return $hash.$hex;
}
?>

<div class="tab-deal">
    <ul id="tabs" class="tabs" >
        <li class="featured">
            <a href="<?php echo Mage::getBaseUrl(); ?>">
                <span>Deal van de Dag</span>
            </a>
        </li>
        <li >
            <a href="<?php echo Mage::helper('dailydeal')->getUrlHttp('dailydeal/index'); ?>">
                <span>Alle Deals</span>
            </a>
        </li>
        <li class="past active">
            <a href="<?php echo Mage::helper('dailydeal')->getUrlHttp('dailydeal/past'); ?>">
                <span>Gemiste Deals</span>
            </a>
        </li>
    </ul>
</div>

<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_pastdealsCollection = $this->getPastdeals();
    $_helper = $this->helper('catalog/output');
?>

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_abc')->toHtml(); ?>

<?php if (!$_pastdealsCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products responsive-list list-actdeals deals-block past-deals">

        <?php // List mode ?>

        <?php
        echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe4.phtml')->toHtml();
        ?>
        <div style="clear:both"></div>
        <?php $_iterator = 0; ?>
        <ol class="products-list" id="products-list">
            <?php foreach ($_pastdealsCollection as $_pastdeal): ?>
                <?php
                $dealqty = $_pastdeal->getDealQty();
                $soldqty = $_pastdeal->getSoldQty();

                $_product = Mage::getModel('catalog/product')->load($_pastdeal->getProductId());

                Mage::unregister('product');
                Mage::register('product', $_product);

                ?>
                <li class="item<?php if (++$_iterator == sizeof($_pastdealsCollection)): ?> last<?php endif; ?> product-view">
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a></h2>
                    <?php // Product Image ?>

                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image horizontal-image product-img-box">
                        <img class="image-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                    </a>
                    <?php // Product description ?>
                    <div class="horizontal-shop product-shop">
                        <div class="f-fix">

                            <?php //echo $this->getPriceHtml($_product, true) ?>
                            <?php
                            $_coreHelper = $this->helper('core');
                            $_taxHelper = $this->helper('tax');
                            $_regularPrice = $_taxHelper->getPrice($_product, $_product->getPrice());
                            $_finalPrice = $_pastdeal->getDailydealPrice();
                            ?>

                            <div class="price-block">
                                <?php if($_pastdeal->checkDealPrice($_product)){ ?>

                                    <p class="old-price" >
                                        <span class="regular-price" id="product-price<?php echo $this->getIdSuffix() ?>-related">
                                            <span class="price">Van <?php echo $_coreHelper->currency($_regularPrice, true, false) ?>,-</span>
                                        </span>
                                    </p>

                                    <p class="special-price">
                                    <span class="price" id="product-price-<?php echo $this->getIdSuffix() ?>">
                                        Voor <?php echo $_coreHelper->currency($_finalPrice, true, false) ?>,-
                                    </span>
                                    </p>
                                <?php
                                }
                                else{
                                    $_pastdeal->setMinPriceFollowProductType($_product);?>
                                    <p class="special-price">
                                    <span class="price" id="product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
                                        <?php echo Mage::helper('dailydeal')->__('Special Price:'); ?>
                                        <?php echo $_coreHelper->currency($_product->getData('min_price'), true, false) ?>
                                    </span>
                                    </p>

                                <?php } ?>
                            </div>
                            <div class="discount-block">
                                <?php
                                    echo -round((1.0-$_finalPrice/$_regularPrice)*100);
                                ?>%
                            </div>
                            <div style="clear: both"></div>

                            <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>

                            <div class="desc std">
                                <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                <a  class="link-learn more-info">Volledige specificatie...</a>
                            </div>

                        </div>
                    </div>

                    <div style="clear: both"> </div>

                    <div class="checkout_box">
                        <div class="mwdld_display_cate">
                            <?php
                            $endtime = strtotime($_pastdeal->getEndDateTime());

                            //$_monthname = date("F j, Y, g:i a",$endtime);
                            $_monthname = date("F" , $endtime);
                            $_date = date("j" , $endtime);
                            $_year = date("Y" , $endtime);

                            ?>
                            <div class="past_date">
                                <?php echo $_date ?> <?php echo $this->__($_monthname); ?> <?php echo $_year ?>
                            </div>
                        </div>
                        <?php
                        $stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product);

                        if (($stock->getQty() > 0) && ($stock->getIsInStock() )){
                        ?>
                        <div class="buy_yet">
                            <button type="button" title="In winkelwagen" class="button btn-cart" onclick="window.location.href = '<?php echo $_product->getProductUrl(); ?>'">
                                <span><span>Als nog kopen?</span></span>
                            </button>
                        </div>
                        <?php
                        }
                        ?>

                    </div>

                    <?php
                    echo $this->getLayout()->createBlock('catalog/product_view_attributes')->setTemplate('catalog/product/view/attributes.phtml')->toHtml();
                    ?>

                    <div class="hr"></div>

                </li>
            <?php endforeach; ?>
        </ol>
        <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    </div>
<?php endif; ?>

